Repository WorkshopMDS/vivatech-app, pull requests merged in 2023-05, with the labels that each got.

#1 Story/wor 44/add navigation to rn app
  .eslintrc.json
  App.tsx
  app/Navigation.tsx
  app/views/Home.tsx
  app/views/QRCode.tsx
  assets/gradient.png
  assets/logo.png
  package.json
  yarn.lock
Labels: PR: Review TODO

#2 Story/wor 45/implement graphical charter from vivatech
  App.tsx
  app.json
  app/Navigation.tsx
  app/Theme.ts
  app/views/QRCode.tsx
  assets/fonts/MuseoSans-100.otf
  assets/fonts/MuseoSans-300.otf
  assets/fonts/MuseoSans_500.otf
  assets/fonts/MuseoSans_700.otf
  assets/fonts/MuseoSans_900.otf
  package.json
  yarn.lock
Labels: PR: Review OK

#3 Story/wor 47/implementer une vue basique pour afficher un qr code
  .eslintrc.json
  .gitignore
  App.tsx
  app.json
  app/Navigation.tsx
  app/components/QRCode/QRCodeModal.tsx
  app/components/QRCode/QRCodeModalBackground.tsx
  app/components/QRCode/QRCodeView.tsx
  app/utils/QRCode.ts
  app/utils/Theme.ts
  app/utils/useToggle.ts
  app/views/Home.tsx
  app/views/QRCode.tsx
  assets/full_small.png
  assets/small.png
  assets/vivatech.jpg
  babel.config.js
  eas.json
  index.js
  metro.config.js
  package.json
  yarn.lock
Labels: PR: Review OK

#4 Story/wor 50/ajouter une vue pour scanner un qr code physique et lenregistrer dans le local storage
  App.tsx
  app.json
  app/Navigation.tsx
  app/components/QRCode/QRCodeModal.tsx
  app/components/QRCode/QRCodeModalBackground.tsx
  app/components/QRCode/QRCodeView.tsx
  app/views/QRCodeScannerView.tsx
  assets/header_dark.png
  assets/header_light.png
  package.json
  yarn.lock
Labels: PR: Review TODO

#5 Fix QR Code Scanner
  app/views/QRCodeScannerView.tsx
  package.json
  yarn.lock
Labels: effort: small, PR: Review OK

#6 Update Theme to be able to customize darkmode custom colors
  .eslintrc.json
  App.tsx
  app/Navigation.tsx
  app/utils/Theme.ts
  app/views/Home.tsx
Labels: PR: Review TODO

#8 Story/wor 63/implement a basic store with redux
  .eslintrc.json
  App.tsx
  app/Navigation.tsx
  app/components/QRCode/QRCodeView.tsx
  app/hooks/index.ts
  app/store/actions/tickets.actions.ts
  app/store/actions/types.ts
  app/store/reducers/index.ts
  app/store/reducers/tickets.reducer.ts
  app/store/services/tickets.service.ts
  app/store/store.ts
  app/utils/useToggle.ts
  app/views/QRCodeScannerView.tsx
  package.json
  yarn.lock
Labels: PR: Review OK

#9 Create new composant and add new validation ticket methods
  .eslintrc.json
  app/components/QRCode/CodeValidation.tsx
  app/components/QRCode/QRCodeModal.tsx
  app/components/QRCode/QRCodeView.tsx
  app/store/actions/tickets.actions.ts
  app/store/actions/types.ts
  app/store/reducers/tickets.reducer.ts
  app/store/services/tickets.service.ts
  app/views/QRCodeScannerView.tsx
  eas.json
  package.json
  yarn.lock
Labels: PR: Review OK

#10 Story/wor 69/scan du cv cv theque
  .eslintrc.json
  app.json
  app/Navigation.tsx
  app/components/QRCode/QRCodeModal.tsx
  app/components/QRCode/QRCodeView.tsx
  app/store/actions/cv.actions.ts
  app/store/actions/types.ts
  app/store/reducers/cv.reducer.ts
  app/store/reducers/index.ts
  app/utils/Theme.ts
  app/views/CVTheque.tsx
  app/views/QRCodeScannerView.tsx
  app/views/ViewCV.tsx
  assets/allwhite.png
  package.json
  yarn.lock
Labels: PR: Review TODO

#12 Story/wor 70/add cache for logging and cv
  App.tsx
  app/components/Exhibitors/ExhibitorStack.tsx
  app/store/actions/cv.actions.ts
  app/store/actions/tickets.actions.ts
  app/store/reducers/cv.reducer.ts
  app/store/reducers/tickets.reducer.ts
  assets/adaptive-icon.png
  assets/icon.png
  assets/splash.png
  package.json
Labels: PR: Review OK

#15 Story/wor 20/views for conferences
  app/Navigation.tsx
  app/components/Conference/ConferenceCard.tsx
  app/models/ConferenceType.ts
  app/store/actions/conference.actions.ts
  app/store/actions/types.ts
  app/store/reducers/conferences.reducer.ts
  app/store/reducers/index.ts
  app/store/services/conference.service.ts
  app/views/ConferenceView.tsx
  app/views/Home.tsx
  package.json
  yarn.lock
Labels: PR: Review OK

#16 Story/wor 26/formulaire dimportation du cv
  .eslintrc.json
  app/Navigation.tsx
  app/components/QRCode/QRCodeModal.tsx
  app/components/QRCode/QRCodeView.tsx
  app/store/actions/cv.actions.ts
  app/store/actions/tickets.actions.ts
  app/store/actions/types.ts
  app/store/reducers/tickets.reducer.ts
  app/store/services/cv.service.ts
  app/store/services/tickets.service.ts
  app/store/services/users.service.ts
  app/utils/auth.ts
  app/views/Profile.tsx
  app/views/QRCodeScannerView.tsx
  package.json
  yarn.lock
Labels: PR: Review OK

#17 Update Conference Cards & Update CV Model
  app/Navigation.tsx
  app/components/Conference/ConferenceCard.tsx
  app/components/Exhibitors/ExhibitorCard.tsx
  app/components/Filter/FilterCard.tsx
  app/models/ConferenceType.ts
  app/store/actions/conference.actions.ts
  app/store/actions/cv.actions.ts
  app/store/reducers/cv.reducer.ts
  app/store/services/conference.service.ts
  app/store/services/cv.service.ts
  app/views/CVTheque.tsx
  app/views/ConferenceView.tsx
  app/views/QRCodeScannerView.tsx
  app/views/ViewCV.tsx
  package.json
  yarn.lock
Labels: PR: Review TODO

#18 Fix Design for journey
  app/components/Conference/ConferenceCard.tsx
  app/components/Exhibitors/ExhibitorCard.tsx
  app/store/services/users.service.ts
  app/utils/auth.ts
  app/views/Journeys/JourneyItemView.tsx
  app/views/Journeys/JourneyResult.tsx
  app/views/Journeys/JourneysListView.tsx
  app/views/Questions/QRCodeQuestionView.tsx
  app/views/Questions/QuestionView.tsx
  app/views/Questions/QuestionsManager.tsx
  app/views/Questions/ResponsesComponent.tsx
  app/views/Questions/TutorialQuestionView.tsx
Labels: PR: Review OK

#19 task/WOR-78/supprimer-la-demande-de-scan-de-qr-code-sur-un-meme-stand
  app/Navigation.tsx
  app/views/Journeys/JourneyItemView.tsx
  app/views/Journeys/JourneyResult.tsx
  app/views/Questions/QRCodeQuestionView.tsx
  app/views/Questions/QuestionView.tsx
  app/views/Questions/QuestionsManager.tsx
  app/views/Questions/ResponsesComponent.tsx
  app/views/Questions/TutorialQuestionView.tsx
Labels: PR: Review TODO
